name: Wikipedia Extraction

on: [pull_request,push]

jobs:
  extract:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    - uses: hecrj/setup-rust-action@e0938bab41405f7485391869b453779c5290099d
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Get Commit Message
      run: echo "COMMIT_MESSAGE=\"$(git log --format=%B -n 1 ${{ github.event.after }})\"" >> $GITHUB_ENV

    - uses: futuratrepadeira/changed-files@b4ef6fe532b9b5022be2489df114ba28146aea14
      if: "contains( github.ref , 'pull' )"
      id: files
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Full Wikipedia Extraction
      if: "contains( env.COMMIT_MESSAGE , '--full-wiki-extraction' )"
      run: ./scripts/wiki-extraction.sh extract
      env:
        FILES_CREATED: ${{ steps.files.outputs.files_created }}
        FILES_UPDATED: ${{ steps.files.outputs.files_updated }}

    - name: Sample Wikipedia Extraction
      if: "!contains( env.COMMIT_MESSAGE , '--full-wiki-extraction' )"
      run: ./scripts/wiki-extraction.sh
      env:
        FILES_CREATED: ${{ steps.files.outputs.files_created }}
        FILES_UPDATED: ${{ steps.files.outputs.files_updated }}

    - name: Deduplicate Wikipedia Extraction
      if: "contains( env.COMMIT_MESSAGE , '--full-wiki-extraction' )"
      run: ./scripts/dedupe.sh wiki.txt

    - uses: actions/upload-artifact@v2
      with:
        name: extraction
        path: output/*

    - uses: actions/upload-artifact@v2
      with:
        name: wikiextractor-output
        path: text/*
